### ISSUE TITLE
Can't compile with Xcode 10.2

### ISSUE THREAD

**Issue by raysarebest** [crowdconnected/colocator-ios#1]
Xcode 10.2 was released yesterday, with support for Swift 5, and dropping support for Swift 3. However, the versions of [ReSwift](https://github.com/ReSwift/ReSwift) and [SwiftProtobuf](https://github.com/apple/swift-protobuf) referenced in the [Cartfile](https://github.com/crowdconnected/colocator-ios/blob/5771f734a597a900313866042c4b248322cddb25/Cartfile#L1) were written in Swift 3, so Xcode 10.2 refuses to compile them

**Comment by ghost** [comment]
Hi @raysarebest. This issue is resolved by version 2.1.3 of our library which was released today
