### ISSUE TITLE
Enable bitcode

### ISSUE THREAD

**Issue by pziemkowski** [crowdconnected/colocator-ios#2]
Is it possible to set ENABLE_BITCODE setting to YES?

I want to install Colocator using Carthage and I wouldn't like to disable bitcode in the whole app just because of a small tracking library.

**Comment by ghost** [comment]
Hi @pziemkowski. This library requires an active commercial license with us, are you working with one of our licencees?

**Comment by pziemkowski** [comment]
Yes, I am working for a client that has an active license. Although I cannot disclose which one.

**Comment by ghost** [comment]
We only support integrators with an active license, without knowing the licensee we can't support you. If you can send this information privately then please email support@crowdconnected.co.uk.
